const defaultTheme = {
  cardWidth: 250,
  thumbWidth: 84,
  thumbHeight: 84,
  labelFontSize: 13,
  cardPadding: 2,
  descriptionDisplay: "inline",
  datesDisplay: "block",
  datesFontSize: 11,
  cardVerticalSpacing: 80,
  nodeDisplay: "flex",
  imageCounter: "block",
  siblingSpouseSeparation: 1.1,
  sameGroupSeparation: 1.16,
  cousinsSeparation: 1.3,
};
export const THEMES = [
  {
    ...defaultTheme,
    name: "Default",
  },
  {
    ...defaultTheme,
    name: "Big",
    labelFontSize: 16,
    datesFontSize: 9,
    cardPadding: 0,
  },
  {
    ...defaultTheme,
    name: "Light",
    cardWidth: 260,
    thumbWidth: 60,
    thumbHeight: 84,
    labelFontSize: 16,
    cardPadding: 0,
    backgroundColor: "rgb(250, 238, 222)",
  },
  { name: "Dark", disabled: true },
  {
    ...defaultTheme,
    name: "Only Label",
    cardWidth: 170,
    labelFontSize: 16,
    descriptionDisplay: "none",
    datesFontSize: 14,
    yearOnly: true,
    cardPadding: 0,
    imageCounter: "none",
    cardVerticalSpacing: 60,
  },
  {
    ...defaultTheme,
    name: "Vertical",
    graphBackgroundColor: "#eae1c7",
    thumbWidth: 80,
    thumbHeight: 80,
    cardWidth: 82,
    cardHeight: 135,
    labelFontSize: 14,
    flexDirection: "column",
    descriptionDisplay: "none",
    datesDisplay: "none",
    yearOnly: true,
    datesFontSize: 14,
    cardPadding: 0,
    imageCounter: "none",
    cardVerticalSpacing: 60,
    siblingSpouseSeparation: 1.25,
    sameGroupSeparation: 1.25,
    cousinsSeparation: 1.35,
  },
].map((theme) => {
  return {
    ...theme,
    cardHeight: theme.cardHeight
      ? theme.cardHeight
      : theme.thumbHeight + 2 * (theme.cardPadding || 0),
  };
});
