export const CARD_WIDTH = 240;
export const CARD_GAP = 10;
export const CARD_PADDING = 5;
export const CARD_INNER_WIDTH = CARD_WIDTH - 2 * CARD_PADDING - 2; //borderrrr
export const IMAGE_HEIGHT = 80;
export const CARD_HEIGHT = IMAGE_HEIGHT + 2 * CARD_PADDING;
export const CARD_VERTICAL_SPACING = CARD_HEIGHT + 100;
export const CARD_OUTER_WIDTH = CARD_WIDTH + CARD_GAP;
export const SIBLING_SPOUSE_SEPARATION = 1.05;
export const SAME_GROUP_SEPARATION = 1.1;
