export const CARD_WIDTH = 250;
export const CARD_PADDING = 3;
export const CARD_BORDER_WIDTH = 1;
export const CARD_INNER_WIDTH =
  CARD_WIDTH - 2 * CARD_PADDING - 2 * CARD_BORDER_WIDTH;
export const IMAGE_SIZE = 82;
export const CARD_CONTENT_WIDTH = CARD_INNER_WIDTH - IMAGE_SIZE;
export const CARD_HEIGHT =
  IMAGE_SIZE + 2 * CARD_PADDING + 2 * CARD_BORDER_WIDTH;
export const CARD_VERTICAL_GAP = 80;
export const CARD_VERTICAL_SPACING = CARD_HEIGHT + CARD_VERTICAL_GAP;
export const SIBLING_SPOUSE_SEPARATION = 1.1;
export const SAME_GROUP_SEPARATION = 1.16;
export const COUSINS_SEPARATION = 1.3;
export const EXPAND_SIDE_BUTTON_GAP = 30;
export const MAX_SCALE = 2;
export const MIN_SCALE = 0;
